package token;

public enum TokenType {
    STRING_TYPE, STRING_LITERAL,
    NUMBER_TYPE, NUMBER_LITERAL,
    LET, IDENTIFIER,
    ASSIGN, COLON, SEMI_COLON, QUOTATION,
    SPACE, TAB, NEW_LINE,
    ADDITION, SUBSTRACTION, DIVISION, MULTIPLICATION,
    PRINT, LEFT_PAREN, RIGHT_PAREN,
    UNKOWN
}
